export const algorithmConstants = {
    GET_SORTING_ALGORITHM_REQUEST: "GET_SORTING_ALGORITHM_REQUEST",
    GET_SORTING_ALGORITHM_SUCCESS: "GET_SORTING_ALGORITHM_SUCCESS",
    GET_SORTING_ALGORITHM_FAILURE: "GET_SORTING_ALGORITHM_FAILURE",
}