export const algorithmConstants = {
    GET_SORTING_ALGORITHM_REQUEST: "GET_SORTING_ALGORITHM_REQUEST",
    GET_SORTING_ALGORITHM_SUCCESS: "GET_SORTING_ALGORITHM_SUCCESS",
    GET_SORTING_ALGORITHM_FAILURE: "GET_SORTING_ALGORITHM_FAILURE",
}

export const algoRunningConstants = {
    ALGO_BUBBLE_SORT_RUNNING: "ALGO_BUBBLE_SORT_RUNNING",
    ALGO_BUBBLE_SORT_COMPLETE: "ALGO_BUBBLE_SORT_COMPLETE",
}