export const algorithmConstants = {
    GET_SORTING_ALGORITHM_REQUEST: "GET_SORTING_ALGORITHM_REQUEST",
    GET_SORTING_ALGORITHM_SUCCESS: "GET_SORTING_ALGORITHM_SUCCESS",
    GET_SORTING_ALGORITHM_FAILURE: "GET_SORTING_ALGORITHM_FAILURE",
}

export const arrayValuesConstants = {
    GET_ARRAY_VALUES_REQUEST: 'GET_ARRAY_VALUES_REQUEST',
    GET_ARRAY_VALUES_SUCCESS: 'GET_ARRAY_VALUES_SUCCESS',
    GET_ARRAY_VALUES_FAILURE: 'GET_ARRAY_VALUES_FAILURE',
}

export const generatingStepsConstants = {
    GENERATING_SORTING_STEPS_REQUEST: 'GENERATING_SORTING_STEPS_REQUEST',
    GENERATING_SORTING_STEPS_SUCCESS: 'GENERATING_SORTING_STEPS_SUCCESS',
    GENERATING_SORTING_STEPS_FAILURE: 'GENERATING_SORTING_STEPS_FAILURE',
    RESET_STEPS:'RESET_STEPS'
}